version: "3"  
services:  
  cassandra00:
    restart: always
    image: cassandra:latest
    volumes: 
      - /Users/amitabhprasad/my-app-data/bookstore-app/cassandra/datadir2
    ports: 
      #- 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
      - 9160:9160
    environment:
      - CASSANDRA_RPC_ADDRESS=127.0.0.1
      - CASSANDRA_BROADCAST_ADDRESS=127.0.0.1
      - CASSANDRA_LISTEN_ADDRESS=127.0.0.1
      - CASSANDRA_START_RPC=true